### ISSUE TITLE
Question: how is operationStore reactive to slug changes?

### ISSUE THREAD

**Issue by thojanssens** [spences10/sveltekit-with-urql#22]
Hello, I have a question:

In the code below
```javascript
const post = operationStore(productQuery, { slug })
query(post)
```
how is the query re-executed if the slug changes?

**Comment by spences10** [comment]
Hey!

I'm not sure I understand the question, the slug change passed into the operation store will have the query with that variable added to it and the `query(post)` executes it, I presume 😊
